[build]
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/dotcyril"
  status = 301
  force = true

[[redirects]]
  from = "/crowdopinion"
  to = "https://virtual2023.aclweb.org/paper_P197.html"
  status = 301
  force = true

[[redirects]]
  from = "/disco"
  to = "https://virtual2023.aclweb.org/paper_P2024.html"
  status = 301
  force = true

[[redirects]]
  from = "/voiced"
  to = "https://cyrilw.com/publication/weerasooriya-2023/"
  status = 301
  force = true